# Generated by Django 5.1.6 on 2025-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Administrator'), (2, 'Teacher'), (3, 'Student'), (4, 'Canteen')], default=1, max_length=50),
        ),
    ]
