# Generated by Django 5.1.6 on 2025-02-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0004_classroom_remove_student_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
