# Generated by Django 5.1.6 on 2025-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0008_canteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('deactivated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
