# Generated by Django 5.1.6 on 2025-02-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0009_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user_name',
        ),
        migrations.AddField(
            model_name='card',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kidsafe_app.student'),
        ),
    ]
