# Generated by Django 5.1.6 on 2025-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0010_remove_card_user_name_card_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
