# Generated by Django 5.1.6 on 2025-02-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0015_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_allergy', models.TextField(blank=True, null=True)),
                ('dietary_restriction', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsafe_app.student')),
            ],
        ),
    ]
