# Generated by Django 5.1.6 on 2025-02-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0016_dietarydetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DietaryDetail',
            new_name='Dietary',
        ),
    ]
