# Generated by Django 5.1.6 on 2025-02-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0021_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
