# Generated by Django 5.1.6 on 2025-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0025_studentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
