# Generated by Django 5.1.6 on 2025-02-28 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0026_examresult_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='title',
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsafe_app.examtitle'),
        ),
    ]
