# Generated by Django 5.1.6 on 2025-03-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0028_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietary',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kidsafe_app.student'),
        ),
    ]
