# Generated by Django 5.1.6 on 2025-03-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0030_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
