# Generated by Django 5.1.6 on 2025-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0031_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='restrictions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
