# Generated by Django 5.1.6 on 2025-04-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0034_alter_inventoryitem_image_teachernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherNotification',
        ),
    ]
