# Generated by Django 5.1.6 on 2025-04-10 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0036_teachernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachernotification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/notifications/teacher/'),
        ),
        migrations.CreateModel(
            name='CanteenNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='media/notifications/canteen/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidsafe_app.canteen')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
