# Generated by Django 5.1.6 on 2025-04-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0038_studentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotification',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to='kidsafe_app.student'),
        ),
    ]
