# Generated by Django 5.1.6 on 2025-04-12 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0039_studentnotification_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnotification',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='studentnotification',
            name='read_by',
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kidsafe_app.student'),
        ),
    ]
