# Generated by Django 5.1.6 on 2025-04-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0041_feedbacktoadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackToAdmin',
        ),
    ]
