# Generated by Django 5.1.6 on 2025-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0043_feedbacktoadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktoadmin',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/feedback/'),
        ),
    ]
