# Generated by Django 5.1.6 on 2025-04-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0044_alter_feedbacktoadmin_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
    ]
