# Generated by Django 5.1.6 on 2025-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0045_remove_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietary',
            name='dietary_restriction',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dietary',
            name='food_allergy',
            field=models.JSONField(default=list),
        ),
    ]
