# Generated by Django 5.1.6 on 2025-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0046_alter_dietary_dietary_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='allergies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='restrictions',
            field=models.JSONField(default=list),
        ),
    ]
