# Generated by Django 5.1.6 on 2025-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0047_alter_inventoryitem_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='allergies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='restrictions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
