# Generated by Django 5.1.6 on 2025-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidsafe_app', '0048_alter_inventoryitem_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='restrictions',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='dietary_restriction',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='food_allergy',
            field=models.JSONField(default=list),
        ),
    ]
